name: AutoCheckIn

on:
  schedule:
    - cron: 0 0 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sgxc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: checkin
        run: |
          python ./ever_photo.py
        env:
          EVER_PHOTO_DATA: ${{ secrets.EVER_PHOTO_DATA }}
